// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	model "server/model"

	mock "github.com/stretchr/testify/mock"
)

// ITodoRepo is an autogenerated mock type for the ITodoRepo type
type ITodoRepo struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *ITodoRepo) Save(_a0 *model.Task) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Task) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITodoRepo creates a new instance of ITodoRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITodoRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITodoRepo {
	mock := &ITodoRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
